#!/usr/bin/env python3
"""Fake ProFTPD. Accepts every login, serves fabricated listings, sinks uploads.

Zero-trust: STOR data is counted and dropped, RETR sends generated bytes, and no
attacker-supplied path ever reaches a real filesystem call.
"""

import asyncio
import os
import random
import sys
import time
from datetime import datetime, timezone

sys.path.insert(0, "/app")

from shared import alerting, identity, persona, tarpit  # noqa: E402

LISTEN_HOST = os.getenv("LISTEN_HOST", "0.0.0.0")
LISTEN_PORT = int(os.getenv("LISTEN_PORT", "2121"))
PASV_PORT_MIN = int(os.getenv("FTP_PASV_MIN", "30000"))
PASV_PORT_MAX = int(os.getenv("FTP_PASV_MAX", "30099"))
SERVICE = "ftp"

TARPIT_DELAY = float(os.getenv("FTP_TARPIT_DELAY", "5.0"))
IDLE_TIMEOUT = int(os.getenv("FTP_IDLE_TIMEOUT", "300"))
TARPIT_MAX_SECONDS = int(os.getenv("FTP_TARPIT_MAX_SECONDS", "600"))
MAX_LINE = 2048

FAKE_LISTING = [
    ("drwxr-xr-x", 4, "www-data", "www-data", 4096, "Jan 12 09:41", "wp-content"),
    ("drwxr-xr-x", 2, "www-data", "www-data", 4096, "Jan 08 14:22", "wp-admin"),
    ("drwxr-xr-x", 2, "www-data", "www-data", 4096, "Nov 27 04:51", "wp-includes"),
    ("-rw-r--r--", 1, "www-data", "www-data", 3214, "Jan 14 22:03", "wp-config.php"),
    ("-rw-r--r--", 1, "www-data", "www-data", 418, "Nov 27 04:51", "index.php"),
    ("-rw-r--r--", 1, "www-data", "www-data", 235, "Dec 02 11:18", ".htaccess"),
    ("-rw-r--r--", 1, "root", "root", 48211904, "Jan 14 02:00", "db-backup.sql.gz"),
]


class FTPSession:
    def __init__(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
        self.reader = reader
        self.writer = writer
        peer = writer.get_extra_info("peername") or ("0.0.0.0", 0)
        self.ip = peer[0]
        self.username = ""
        self.cwd = "/var/www/html"
        self.data_server = None
        self.data_target = None
        self.rest = 0
        self.recorder = None
        # Accumulated across the whole session rather than logged per reply:
        # FTP stalls a tarpitted client on every single response, so one event
        # per stall would bury the log to report the same connection.
        self.tarpit_seconds = 0.0
        # Sampled once, then kept: is_tarpitted() was being called on every
        # single reply, which is a Redis round trip per line of a protocol that
        # is nothing but lines. The scored events already return the verdict,
        # so this tracks it without asking again.
        self.tarpitted = False
        self.banned = False
        self.hold_key = None

    def score(self, event_type: str, payload: str = ""):
        """Score, and act on the verdict during this connection, not the next."""
        result = identity.score_named_event(self.ip, event_type,
                                            payload=payload, service=SERVICE)
        if result.get("tarpitted"):
            self.engage()
        if result.get("banned"):
            self.banned = True
        return result

    def engage(self) -> None:
        if not self.tarpitted:
            self.tarpitted = True
            self.rec().write_output("[tarpit engaged]\r\n")
        if self.hold_key is None:
            self.hold_key = tarpit.begin_hold(self.ip, SERVICE, TARPIT_MAX_SECONDS)

    def rec(self):
        """Session recorder, created on the first exchange.

        Lazily, so a bare port scan that opens and drops a connection does not
        leave an empty recording. FTP is a line protocol, so the transcript
        replays as a readable terminal session with no translation needed.
        """
        if self.recorder is None:
            self.recorder = alerting.SessionRecorder(
                self.ip, SERVICE, title=f"ftp from {self.ip}")
        return self.recorder

    async def reply(self, code: int, message: str) -> None:
        if self.tarpitted:
            started = time.monotonic()
            try:
                await asyncio.sleep(TARPIT_DELAY)
            finally:
                self.tarpit_seconds += time.monotonic() - started
        self.rec().write_output(f"{code} {message}\r\n")
        self.writer.write(f"{code} {message}\r\n".encode())
        await self.writer.drain()

    async def open_data(self):
        """Return a (reader, writer) pair for whichever data mode was negotiated."""
        if self.data_server is not None:
            try:
                return await asyncio.wait_for(self.data_server["future"], timeout=20)
            except asyncio.TimeoutError:
                return None
        if self.data_target is not None:
            host, port = self.data_target
            try:
                return await asyncio.wait_for(
                    asyncio.open_connection(host, port), timeout=15)
            except (OSError, asyncio.TimeoutError):
                return None
        return None

    async def close_data(self) -> None:
        if self.data_server is not None:
            self.data_server["server"].close()
            try:
                await self.data_server["server"].wait_closed()
            except Exception:
                pass
            self.data_server = None
        self.data_target = None

    # ------------------------------------------------------------- commands

    async def cmd_user(self, arg: str) -> None:
        self.username = arg[:128]
        if arg.lower() in ("anonymous", "ftp"):
            self.score("FTP_ANON", arg[:120])
        await self.reply(331, f"Password required for {arg}")

    async def cmd_pass(self, arg: str) -> None:
        identity.record_credential(self.ip, self.username, arg, SERVICE)
        self.score("CREDENTIAL_ATTEMPT", f"{self.username}:{arg}"[:200])
        if identity.detect_spray(self.ip):
            self.score("CREDENTIAL_SPRAY")
            identity.activate_tarpit(self.ip, "FTP credential spray", SERVICE)
            self.engage()
        await self.reply(230, f"User {self.username} logged in")

    async def cmd_syst(self, _arg: str) -> None:
        await self.reply(215, "UNIX Type: L8")

    async def cmd_feat(self, _arg: str) -> None:
        self.writer.write(b"211-Features:\r\n MDTM\r\n MFMT\r\n LANG en-US\r\n"
                          b" REST STREAM\r\n SIZE\r\n TVFS\r\n UTF8\r\n211 End\r\n")
        await self.writer.drain()

    async def cmd_pwd(self, _arg: str) -> None:
        await self.reply(257, f'"{self.cwd}" is the current directory')

    async def cmd_cwd(self, arg: str) -> None:
        self.score("RECON_LS", f"CWD {arg}"[:120])
        if arg.startswith("/"):
            self.cwd = arg.rstrip("/") or "/"
        else:
            self.cwd = (self.cwd.rstrip("/") + "/" + arg).rstrip("/")
        await self.reply(250, "CWD command successful")

    async def cmd_cdup(self, _arg: str) -> None:
        self.cwd = os.path.dirname(self.cwd.rstrip("/")) or "/"
        await self.reply(250, "CDUP command successful")

    async def cmd_type(self, arg: str) -> None:
        await self.reply(200, f"Type set to {arg.upper() or 'I'}")

    async def cmd_pasv(self, _arg: str) -> None:
        await self.close_data()
        loop = asyncio.get_running_loop()
        future = loop.create_future()

        def on_connect(reader, writer):
            if not future.done():
                future.set_result((reader, writer))

        port = random.randint(PASV_PORT_MIN, PASV_PORT_MAX)
        try:
            server = await asyncio.start_server(on_connect, "0.0.0.0", port)
        except OSError:
            await self.reply(425, "Can't open passive connection")
            return
        self.data_server = {"server": server, "future": future, "port": port}

        advertised = os.getenv("FTP_PASV_ADDRESS", "").strip()
        host = advertised or (self.writer.get_extra_info("sockname") or ("127.0.0.1",))[0]
        octets = host.split(".")
        if len(octets) != 4:
            octets = ["127", "0", "0", "1"]
        await self.reply(227, "Entering Passive Mode ({},{},{})".format(
            ",".join(octets), port >> 8, port & 0xFF))

    async def cmd_port(self, arg: str) -> None:
        await self.close_data()
        parts = arg.split(",")
        if len(parts) != 6:
            await self.reply(501, "Illegal PORT command")
            return
        try:
            host = ".".join(parts[:4])
            port = (int(parts[4]) << 8) + int(parts[5])
        except ValueError:
            await self.reply(501, "Illegal PORT command")
            return
        self.data_target = (host, port)
        await self.reply(200, "PORT command successful")

    async def cmd_list(self, arg: str) -> None:
        self.score("RECON_LS", f"LIST {arg}"[:120])
        await self.reply(150, "Opening ASCII mode data connection for file list")
        pair = await self.open_data()
        if pair is None:
            await self.reply(425, "Can't open data connection")
            return
        _, writer = pair
        body = "".join(
            f"{mode}  {links} {owner:<8} {group:<8} {size:>12} {stamp} {name}\r\n"
            for mode, links, owner, group, size, stamp, name in FAKE_LISTING
        )
        try:
            writer.write(body.encode())
            await writer.drain()
            writer.close()
        except OSError:
            pass
        await self.close_data()
        await self.reply(226, "Transfer complete")

    async def cmd_nlst(self, arg: str) -> None:
        self.score("RECON_LS", f"NLST {arg}"[:120])
        await self.reply(150, "Opening ASCII mode data connection for file list")
        pair = await self.open_data()
        if pair is None:
            await self.reply(425, "Can't open data connection")
            return
        _, writer = pair
        try:
            writer.write("".join(f"{row[6]}\r\n" for row in FAKE_LISTING).encode())
            await writer.drain()
            writer.close()
        except OSError:
            pass
        await self.close_data()
        await self.reply(226, "Transfer complete")

    async def cmd_retr(self, arg: str) -> None:
        self.score("FILE_DOWNLOAD", f"RETR {arg}"[:200])
        await self.reply(150, f"Opening BINARY mode data connection for {arg}")
        pair = await self.open_data()
        if pair is None:
            await self.reply(425, "Can't open data connection")
            return
        _, writer = pair
        try:
            writer.write(bytes(random.getrandbits(8) for _ in range(200)))
            await writer.drain()
            writer.close()
        except OSError:
            pass
        await self.close_data()
        self.rec().write_output(f"[data] sent 200 bytes for {arg}\r\n")
        await self.reply(226, "Transfer complete")

    async def cmd_stor(self, arg: str) -> None:
        """Accept the upload, count the bytes, keep nothing."""
        self.score("FILE_UPLOAD", f"STOR {arg}"[:200])
        identity.activate_tarpit(self.ip, "FTP upload attempt", SERVICE)
        self.engage()
        await self.reply(150, f"Opening BINARY mode data connection for {arg}")
        pair = await self.open_data()
        if pair is None:
            await self.reply(425, "Can't open data connection")
            return
        reader, writer = pair
        received = 0
        try:
            while received < 50 * 1024 * 1024:
                chunk = await asyncio.wait_for(reader.read(65536), timeout=30)
                if not chunk:
                    break
                received += len(chunk)
            writer.close()
        except (OSError, asyncio.TimeoutError):
            pass
        await self.close_data()
        # The control channel is what gets recorded, so a transfer that happens
        # entirely on the data connection leaves no trace in the replay unless
        # its outcome is written back here.
        self.rec().write_output(
            f"[data] received {received} bytes as {arg}, discarded\r\n")
        alerting.alert_event(
            ip=self.ip, event_type="FTP_UPLOAD_DISCARDED", service=SERVICE,
            reason=f"Discarded {received} bytes uploaded as {arg}",
            payload=arg[:200], upload_bytes=received,
        )
        await self.reply(226, "Transfer complete")

    async def cmd_dele(self, arg: str) -> None:
        await self.reply(250, f"DELE command successful ({arg})")

    async def cmd_mkd(self, arg: str) -> None:
        await self.reply(257, f'"{arg}" directory created')

    async def cmd_rmd(self, arg: str) -> None:
        await self.reply(250, "RMD command successful")

    async def cmd_size(self, _arg: str) -> None:
        await self.reply(213, str(random.randint(1024, 262144)))

    async def cmd_mdtm(self, _arg: str) -> None:
        await self.reply(213, datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S"))

    async def cmd_rest(self, arg: str) -> None:
        try:
            self.rest = int(arg)
        except ValueError:
            self.rest = 0
        await self.reply(350, f"Restarting at {self.rest}")

    async def cmd_noop(self, _arg: str) -> None:
        await self.reply(200, "NOOP command successful")

    async def cmd_quit(self, _arg: str) -> None:
        await self.reply(221, "Goodbye.")

    HANDLERS = {
        "USER": cmd_user, "PASS": cmd_pass, "SYST": cmd_syst, "FEAT": cmd_feat,
        "PWD": cmd_pwd, "XPWD": cmd_pwd, "CWD": cmd_cwd, "XCWD": cmd_cwd,
        "CDUP": cmd_cdup, "TYPE": cmd_type, "PASV": cmd_pasv, "PORT": cmd_port,
        "LIST": cmd_list, "NLST": cmd_nlst, "RETR": cmd_retr, "STOR": cmd_stor,
        "DELE": cmd_dele, "MKD": cmd_mkd, "XMKD": cmd_mkd, "RMD": cmd_rmd,
        "SIZE": cmd_size, "MDTM": cmd_mdtm, "REST": cmd_rest, "NOOP": cmd_noop,
        "QUIT": cmd_quit,
    }


async def handle(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
    session = FTPSession(reader, writer)
    ip = session.ip

    if identity.is_banned(ip):
        writer.close()
        return

    ident = identity.get_or_create_identity(ip)
    identity.score_named_event(ip, "CONNECTION_ANY", service=SERVICE)

    try:
        if identity.is_tarpitted(ip):
            session.engage()
            started = time.monotonic()
            try:
                await asyncio.sleep(TARPIT_DELAY)
            finally:
                session.tarpit_seconds += time.monotonic() - started
        banner = (f"220 {persona.get('ftp_banner')} "
                  f"[::ffff:{ident.get('fake_lan_ip', '10.0.1.50')}]\r\n")
        writer.write(banner.encode())
        await writer.drain()

        while True:
            try:
                raw = await asyncio.wait_for(reader.readline(), timeout=IDLE_TIMEOUT)
            except asyncio.TimeoutError:
                break
            if not raw:
                break
            line = raw[:MAX_LINE].decode("utf-8", "replace").strip()
            if not line:
                continue

            # The banner is written on first use so it lands in the recording
            # ahead of whatever the client says back.
            recorder = session.rec()
            if recorder.frames == 0:
                recorder.write_output(banner)
            recorder.write_output(line + "\r\n")

            verb, _, arg = line.partition(" ")
            verb = verb.upper()
            handler = FTPSession.HANDLERS.get(verb)
            if handler is None:
                await session.reply(500, f"{verb} not understood")
                continue
            await handler(session, arg.strip())
            if verb == "QUIT":
                break
            # The reply to the command that crossed the threshold has already
            # gone out and been recorded; the connection stops here rather than
            # running until the attacker's next one is refused.
            if session.banned:
                recorder.write_output("[banned mid-session, closing]\r\n")
                break
    except (OSError, asyncio.IncompleteReadError):
        pass
    finally:
        tarpit.end_hold(session.hold_key)
        tarpit.log_hold(ip, SERVICE, session.tarpit_seconds)
        if session.recorder is not None:
            if session.tarpit_seconds:
                session.recorder.write_output(
                    f"[tarpit held this connection {session.tarpit_seconds:.0f}s]\r\n")
            session.recorder.close()
        await session.close_data()
        try:
            writer.close()
        except OSError:
            pass


async def main() -> None:
    server = await asyncio.start_server(handle, LISTEN_HOST, LISTEN_PORT)
    print(f"[*] fake ftpd listening on {LISTEN_HOST}:{LISTEN_PORT}", flush=True)
    async with server:
        await server.serve_forever()


if __name__ == "__main__":
    asyncio.run(main())
